spring.application.name=SpringBoot_Backend
# Db2 Connection Settings
spring.datasource.url=jdbc:db2://localhost:50000/shopdb
spring.datasource.username=db2inst1
spring.datasource.password=AdminPassword123!
spring.datasource.driver-class-name=com.ibm.db2.jcc.DB2Driver

# Hibernate / JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:db2://localhost:50000/shopdb:currentSchema=AUTH;